server:
  port: 8088

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/Middleware?useUnicode=true&characterEncoding=utf8
    username: joker
    password: joker
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #初始化时建立物理连接的个数
      initial-size: 3
      #  最小连接池数量
      min-idle: 1
      #最大连接池数量
      max-active: 5
      #获取连接时最大等待时间
      max-wait: 60000
      validation-query: select 1

mybatis:
  type-aliases-package: model
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true